version: '3.8'
services:
  dev-environment:
    build: .
    container_name: dev-environment
    tty: true
    stdin_open: true
    volumes:
      - /mnt/user:/unraid
      - ${NVIM_CONFIG_PATH}:/root/.config/nvim
